#!groovy
//@Library('onprem-shared-library@master') _

pipeline {
    agent any
    stages {
        stage('Get project information') {
            steps {
                script {
                    def name = 'diego'
                    echo "$name"
                    dir("scripts"){
                        sh """
                            pwd
                            ls
                        """
                    }
                }
            }
        }
    }
}